<%@ Page Title="About Project" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AboutProject.aspx.cs" Inherits="KMSABET.KMSPages.AboutProject" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    
    <h3>About Project</h3>
    <br />
    <a class="btn btn-default" target="_blank" href="/MyDocs/KMS for ABET compliant teaching and evaluations v2.pptx">Download Presentation</a>
    <a class="btn btn-default" target="_blank" href="/MyDocs/MVC Design of the system.docx">Download MVC Design of the System</a>
    <a class="btn btn-default" target="_blank" href="/MyDocs/Thesis Project Report - KMS for ABET compliant teaching and evaluations.docx">Download Project Report</a><br/>
    <br />
    <p>Processes to ensure continuous improvement of the quality of a system are called Continuous Quality Improvement (CQI) processes. Academic programs require CQI to attain a certain level of satisfaction of the learning outcomes. These processes are required for a program to be accredited by ABET or other similar accrediting agencies (Prof. Dr. Imam &amp; Prof. Dr. Tasadduq, 2012). While expert system technologies have been successfully developed and deployed in such diverse disciplines as Engineering, Business, Mining, Medicine, etc. (Ahmad et al 2008; Marakas, 2013; Negnevitsky, 2013; Turban and Aronson, 2013), little efforts have been expended in employing decision support and expert system methodologies in the important area of CQI/Accreditation.</p>
    <p>The idea of integrating expert system with the question bank is new. The expert system developed in this project will help the faculty members in designing assessments and suggesting continuous improvement plans for courses in which the required satisfaction is not achieved. The expert system will be dynamic with a knowledge base that will continue to grow with time as more and more knowledge and rules are added to it. Hence we named this project as Expert system (ES) for ABET compliant teaching and evaluations.</p>
    <p>The expert system for improvement of the teaching a course has not been implemented earlier. For CQI, there will be a knowledge base containing rules added by the industry experts. Each rule will be associated with a single CLO (course learning outcome) and each rule yield suggestion(s) for that CLO. The multiple choice questions (MCQs) will be presented to instructor and his/her answers will be processed in an inference engine which will output the suggestion(s) based on the provided rules added by the industry experts.</p>
    <p>Secondly, in this project we would develop an expert system for helping the instructors in selecting the appropriate questions for any type of assessment (in the form of /quizzes/ home works/Midterm/ Final Exams/ term projects etc) of the course. Presently there is no systematic or consistent way for manually designing the type of assessment for which the proposed expert system is required. For the proposed expert system, we are talking about the assessment of learning outcomes. Mostly instructors don&rsquo;t design assessments for learning outcomes. Usually the manual design of assessments focuses on the assessment of the topics or subtopics covered in a course. The idea of an expert system for assessment of learning outcomes of a course which is the root of the CQI and a necessary requirement of ABET Accreditation, is new.</p>
    <p>While manually designing the assessment, the instructor thinks and based on his own judgment, selects a question from the set of questions available to him for the course, or he makes a new question and adds it to the list of questions. The expert system we are proposing will do the inferencing based upon the following:</p>
    <p>A set of technical questions for each subtopic (developed initially and then improved gradually in quantity and quality based on the data gathered from the use of the expert system )</p>
    <p>Each question will have a set of attributes as follows:</p>
    <ol>
    <li>Learning outcome IDs (may be more than 1) that it can test</li>
    <li>Bloom&rsquo;s Level</li>
    <li>Time needed to solve</li>
    <li>How strong is the question in assessing the learning outcomes in (i) above e.g. 10%, 50% or 100% etc</li>
    <li>Topic/Subtopic it addresses</li>
    <li>A set of questions that the expert system interface will ask the instructor</li>
    <li>Possible answers of each question in ( c )</li>
    </ol>
    <p>A set of If-then-else rules to select the right technical question from the set of questions in (a).</p>
    <p>An expert system is a computer system that emulates the decision-making ability of a human expert. Expert systems are designed to solve complex problems by reasoning about knowledge, represented primarily as if&ndash;then rules rather than through conventional procedural code. An expert system is divided into two sub-systems: the inference engine and the knowledge base. The knowledge base represents facts and rules. The inference engine applies the rules to the known facts to deduce new facts.</p>
    <p>The CQI and accreditation processes of engineering education could have potential applications of knowledge-based expert systems. One such area is the &ldquo;assessment design&rdquo; for a specific learning outcome. In this case, the instructor, in a course he/she is teaching, can select the most suitable question(s) for assessing a global learning outcome (e.g., student outcome in ABET terminology) or one of the course learning outcomes. A knowledge base may be built having a variety of questions for each topic or subtopic of the course. Each question can have tags indicating the learning outcome it addresses, time needed to solve the question, level of difficulty, and Bloom&rsquo;s Level etc. A set of if/then/else rules may also be developed and incorporated in the knowledge base. The inference engine will interact with the knowledge base and respond to the user by suggesting appropriate questions for the assessment as shown in Fig. 1.</p>
    <p>Another potential application of expert system in the context of CQI/Accreditation may be in the treatment of a weakness in a particular learning outcome. If at the end of a course, it is found that the satisfaction criterion for an outcome has not been achieved e.g., less than 70% students are able to obtain more than 70% marks in a particular learning outcome, a continuous improvement plan is required to improve the situation when the course is taught next time. The possible treatments may include, more homework, more quizzes, arranging tutorials, re-sequencing the order of topics taught, toughening the admission policy, etc. Similar other areas of possible application of expert system may be explored.</p>
    <p>ABET is a non-profit and non-governmental accrediting agency for academic programs in the disciplines of applied science, computing, engineering, and engineering technology. ABET is a recognized accreditor in the United States (U.S.) by the Council for Higher Education Accreditation.</p>
    <p>ABET accreditation provides assurance that a college or university program meets the quality standards established by the profession for which the program prepares its students. ABET accredits postsecondary programs housed in degree-granting institutions which have been recognized by national or regional institutional accreditation agencies or national education authorities worldwide.</p>
</asp:Content>
